apiVersion: v1
kind: Pod
metadata:
  annotations:
    cni.projectcalico.org/containerID: 587eae58771bcad45affd9dfda1e5a489f3305bbd2eb44b6cd5efd711447f7c8
    cni.projectcalico.org/podIP: 10.233.97.129/32
    cni.projectcalico.org/podIPs: 10.233.97.129/32
  creationTimestamp: "2025-08-27T14:45:38Z"
  generateName: clyde-
  labels:
    app.kubernetes.io/instance: clyde
    app.kubernetes.io/name: clyde
    controller-revision-hash: 679bf8d684
    pod-template-generation: "1"
  name: clyde-6bnns
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: clyde
    uid: 7c728f5b-e908-4a69-9a96-0bcab1d96de4
  resourceVersion: "3705194"
  uid: d0b423f3-e238-4b61-9126-2976fbe8ac39
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - node5
  containers:
  - args:
    - registry
    - --log-level=INFO
    - --mirror-resolve-retries=3
    - --mirror-resolve-timeout=20ms
    - --registry-addr=:5000
    - --router-addr=:5001
    - --metrics-addr=:9090
    - --containerd-sock=/run/containerd/containerd.sock
    - --containerd-namespace=k8s.io
    - --containerd-registry-config-path=/etc/containerd/certs.d
    - --bootstrap-kind=dns
    - --dns-bootstrap-domain=clyde-bootstrap.default.svc.cluster.local.
    - --resolve-latest-tag=true
    - --containerd-content-path=/data/var/lib/containerd/io.containerd.content.v1.content
    - --debug-web-enabled=true
    - --enable-pip-proxy=true
    env:
    - name: GOMEMLIMIT
      valueFrom:
        resourceFieldRef:
          divisor: "1"
          resource: limits.memory
    - name: NODE_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    image: cmc.centralrepo.rnd.huawei.com/clyde/clyde:v29.0
    imagePullPolicy: IfNotPresent
    name: registry
    ports:
    - containerPort: 5000
      hostPort: 30020
      name: registry
      protocol: TCP
    - containerPort: 5001
      name: router
      protocol: TCP
    - containerPort: 9090
      name: metrics
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /healthz
        port: registry
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        memory: 128Mi
      requests:
        memory: 128Mi
    securityContext: {}
    startupProbe:
      failureThreshold: 60
      httpGet:
        path: /healthz
        port: registry
        scheme: HTTP
      periodSeconds: 3
      successThreshold: 1
      timeoutSeconds: 1
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /run/containerd/containerd.sock
      name: containerd-sock
    - mountPath: /data/var/lib/containerd/io.containerd.content.v1.content
      name: containerd-content
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-p2f8w
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - args:
    - configuration
    - --log-level=INFO
    - --containerd-registry-config-path=/etc/containerd/certs.d
    - --mirror-targets
    - http://$(NODE_IP):30020
    - http://$(NODE_IP):30021
    - --resolve-tags=true
    - --prepend-existing=false
    env:
    - name: NODE_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    image: cmc.centralrepo.rnd.huawei.com/clyde/clyde:v29.0
    imagePullPolicy: IfNotPresent
    name: configuration
    resources:
      limits:
        memory: 128Mi
      requests:
        memory: 128Mi
    securityContext: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/containerd/certs.d
      name: containerd-config
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-p2f8w
      readOnly: true
  - args:
    - pip-configuration
    - --log-level=INFO
    - --pip-config-path=/etc
    - --proxy=http://$(NODE_IP):30021
    - --index-url=http://$(NODE_IP):30021/simple
    - --timeout=150
    env:
    - name: NODE_IP
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: status.hostIP
    image: cmc.centralrepo.rnd.huawei.com/clyde/clyde:v29.0
    imagePullPolicy: IfNotPresent
    name: pip-configuration
    resources: {}
    securityContext: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc
      name: pip-config
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-p2f8w
      readOnly: true
  nodeName: node5
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 2000001000
  priorityClassName: system-node-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: clyde
  serviceAccountName: clyde
  terminationGracePeriodSeconds: 30
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoExecute
    operator: Exists
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  volumes:
  - hostPath:
      path: /run/containerd/containerd.sock
      type: Socket
    name: containerd-sock
  - hostPath:
      path: /data/var/lib/containerd/io.containerd.content.v1.content
      type: Directory
    name: containerd-content
  - hostPath:
      path: /etc/containerd/certs.d
      type: DirectoryOrCreate
    name: containerd-config
  - hostPath:
      path: /etc
      type: DirectoryOrCreate
    name: pip-config
  - name: kube-api-access-p2f8w
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2025-08-27T14:45:43Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2025-08-27T14:45:45Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2025-08-27T14:45:45Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2025-08-27T14:45:38Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://11e97f86ade3c1a8fcff7f3a1c123277ae0f115c0d831324dad30cad9f5ead40
    image: cmc.centralrepo.rnd.huawei.com/clyde/clyde:v29.0
    imageID: cmc.centralrepo.rnd.huawei.com/clyde/clyde@sha256:d1d3d764e01edf176e23628d40087992ddd31ddfdaad1b3e9549e7fba45e73b9
    lastState: {}
    name: registry
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2025-08-27T14:45:43Z"
  hostIP: 7.151.7.117
  initContainerStatuses:
  - containerID: containerd://ebbcb2eeb5768cb0b462a72ddbfacc28326edc48ae4d34bcadfbe684fac329cc
    image: cmc.centralrepo.rnd.huawei.com/clyde/clyde:v29.0
    imageID: cmc.centralrepo.rnd.huawei.com/clyde/clyde@sha256:d1d3d764e01edf176e23628d40087992ddd31ddfdaad1b3e9549e7fba45e73b9
    lastState: {}
    name: configuration
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: containerd://ebbcb2eeb5768cb0b462a72ddbfacc28326edc48ae4d34bcadfbe684fac329cc
        exitCode: 0
        finishedAt: "2025-08-27T14:45:41Z"
        reason: Completed
        startedAt: "2025-08-27T14:45:41Z"
  - containerID: containerd://0ce6b028475d6ccb28eaf25eb58b359848f37a0f277d9559efcc839bfb0de991
    image: cmc.centralrepo.rnd.huawei.com/clyde/clyde:v29.0
    imageID: cmc.centralrepo.rnd.huawei.com/clyde/clyde@sha256:d1d3d764e01edf176e23628d40087992ddd31ddfdaad1b3e9549e7fba45e73b9
    lastState: {}
    name: pip-configuration
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: containerd://0ce6b028475d6ccb28eaf25eb58b359848f37a0f277d9559efcc839bfb0de991
        exitCode: 0
        finishedAt: "2025-08-27T14:45:42Z"
        reason: Completed
        startedAt: "2025-08-27T14:45:42Z"
  phase: Running
  podIP: 10.233.97.129
  podIPs:
  - ip: 10.233.97.129
  qosClass: Burstable
  startTime: "2025-08-27T14:45:38Z"
