apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hf-exp
spec:
  selector:
    matchLabels:
      app: hf-exp
  template:
    metadata:
      labels:
        app: hf-exp
    spec:
      # Allow pods to run on control-plane nodes
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"

      containers:
        - name: hf-exp
          image: ghcr.io/clyde-org/hf.exp:v1.1
          imagePullPolicy: Always
          env:
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-secret
                  key: HF_TOKEN
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: HF_ENDPOINT
              value: "http://$(NODE_IP):30020/huggingface"
          volumeMounts:
            - name: hf-cache
              mountPath: /data/cache/hf/model

      volumes:
        - name: hf-cache
          emptyDir: {}

      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - hf-exp
              topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - master-14-ascd
                      - master-16
                      - master-17
                      - master-19
                      - master-20
                      - master-22
                      - worker-10
                      - worker-11
                      - worker-12
                      - worker-23
                      - worker-24
                      - worker-25
                      - worker-26
                      - worker-27
                      - worker-28
                      - worker-29
                      - worker-30
                      - worker-31
                      - worker-32
                      - worker-33
                      - worker-34
                      - worker-35
                      - worker-37
                      - worker-38
                      - worker-39
                      - worker-40
                      - worker-41
